name: Terraform Apply
on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Autheticate to AWS using OICD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654356600:role/github-actions-oidc-example20240410145906668200000001
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Terraform version
        run: |
          terraform version

      - name: Check Go version
        run: go version
